I'm sorry, but an uncaught exception occurred.

While loading <renpy.display.im.Image object ('images/c/default.png') at 0x00000000047feb80>:
  File "renpy/common/00start.rpy", line 207, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 390, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 317, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 342, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
OSError: Couldn't find file 'images/c/default.png'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 207, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 390, in script
    $ __gl_test()
  File "C:\Users\4853597\Desktop\renPy\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\4853597\Desktop\renPy\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00gltest.rpy", line 390, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 317, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 342, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
  File "C:\Users\4853597\Desktop\renPy\renpy-8.1.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\4853597\Desktop\renPy\renpy-8.1.3-sdk\renpy\display\core.py", line 3539, in interact
    self.start()
  File "C:\Users\4853597\Desktop\renPy\renpy-8.1.3-sdk\renpy\display\core.py", line 2462, in start
    surf = renpy.display.im.load_surface(fn)
  File "C:\Users\4853597\Desktop\renPy\renpy-8.1.3-sdk\renpy\display\im.py", line 2070, in load_surface
    return cache.get(image(im))
  File "C:\Users\4853597\Desktop\renPy\renpy-8.1.3-sdk\renpy\display\im.py", line 330, in get
    surf = image.load()
  File "C:\Users\4853597\Desktop\renPy\renpy-8.1.3-sdk\renpy\display\im.py", line 803, in load
    raise e
  File "C:\Users\4853597\Desktop\renPy\renpy-8.1.3-sdk\renpy\display\im.py", line 757, in load
    filelike = renpy.loader.load(self.filename, directory="images")
  File "C:\Users\4853597\Desktop\renPy\renpy-8.1.3-sdk\renpy\loader.py", line 833, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'images/c/default.png'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Frontend Fantasy 1.0
Sun Dec 10 16:48:42 2023
